# Практическое задание №4 по теме "Линейные преобразования". Часть 1

In [1]:
import numpy as np
import copy

## Задание 1

Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

___Решение___

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
0 & 0 & -2 & 3
\end{matrix} \right |
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
$$

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix} \right |
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
$$

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -2 & 2 & 10 \\ 
0 & 0 & -2 & 3
\end{matrix} \right |
\begin{matrix}
0\\ 
-4\\
4
\end{matrix}
\end{pmatrix}
$$

$$\begin{pmatrix}
\left. \begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -2 & 0 & 13 \\ 
0 & 0 & -2 & 3
\end{matrix} \right |
\begin{matrix}
0\\ 
0\\
4
\end{matrix}
\end{pmatrix}
$$

$$n=4$$, 
$$rankA=rank \tilde A = 3$$

По теореме Кронекера — Капелли выполнение условия $rankA=rank \tilde A<n$ означает, что система имеет бесконечное количество решений. Система совместная неопределенная. 

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0 \\
-2x_{2}+13x_{4}=0 \\
-2x_{3}+3x_{4}=4
\end{cases}$$

Запишем общее решение, задав _свободным_ параметром $x_{4}=c$:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2c=0 \\
-2x_{2}+13c=0 \\
-2x_{3}+3c=4
\end{cases} \implies
\begin{cases}
x_{1}=-x_{2}+x_{3}+2c \\
x_{2}=6.5c \\
x_{3}=1.5c - 2
\end{cases} \implies
\begin{cases}
x_{1}=-x_{2}+x_{3}+2c \\
x_{2}=6.5c \\
x_{3}=1.5c - 2
\end{cases}
$$

Общее решение: 
$$\begin{cases}
x_{1}=-3c-2 \\
x_{2}=6.5c \\
x_{3}=1.5c - 2\\
x_{4}=c
\end{cases}$$

---

## Задание 2

Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4 \\
2x_{1}-5x_{2}-3x_{3}=-17 \\
x_{1}+x_{2}-x_{3}=0
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1 \\
x_{1}-2x_{2}+3x_{3}=-2 \\
3x_{1}-6x_{2}+9x_{3}=5
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4 \\
3x_{1}+x_{2}-8x_{3}=-2 
\end{cases}$

___Решение___

Воспользуемся __теоремой Кронекера — Капелли__.

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными считается равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:

$$rank A=rank \tilde A.$$

* если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, то есть имеет единственное решение;<br>
* если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
* если $rankA<rank \tilde A$, то система несовместна.

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4 \\
2x_{1}-5x_{2}-3x_{3}=-17 \\
x_{1}+x_{2}-x_{3}=0
\end{cases}$

$$ A =\begin{pmatrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1
\end{pmatrix}$$

$$\tilde A =\begin{pmatrix}
\left. \begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

$$rankA=3, \; rank\tilde A = 3, \; n=3$$

$$rankA=rank\tilde A=n$$

Система является ___совместной___ и имеет ___единственное решение___.

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1 \\
x_{1}-2x_{2}+3x_{3}=-2 \\
3x_{1}-6x_{2}+9x_{3}=5
\end{cases}$

$$ A =\begin{pmatrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{pmatrix}$$

$$ A =\begin{pmatrix}
1 & -2 & 3 \\ 
\end{pmatrix}$$

$$\tilde A =\begin{pmatrix}
\left. \begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

$$\tilde A =\begin{pmatrix}
\left. \begin{matrix}
1 & -2 & 3 \\ 
0 & 0 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
-2\\ 
5\\
0
\end{matrix}
\end{pmatrix}$$

$$rankA=1, \; rank\tilde A = 2, \; n=3$$

$$rankA<rank\tilde A$$

Система является ___несовместной___ и ___не имеет решений___.

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4 \\
3x_{1}+x_{2}-8x_{3}=-2 
\end{cases}$

$$ A =\begin{pmatrix}
1 & 2 & 5 \\ 
3 & 1 & -8
\end{pmatrix}$$

$$\tilde A =\begin{pmatrix}
\left. \begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

$$rankA=2, \; rank\tilde A = 2, \; n=3$$

$$rankA=rank\tilde A < n$$

Система является ___совместной___ и имеет ___бесконечное количество решений___.

---

## Задание 3

Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$$

___Решение___

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 0\\ 
0 & 5 & 0 & 0\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
\frac{83}{30} \\ 
1.5\\
4\\
1
\end{matrix}
\end{pmatrix}$$

$$rankA=4, \; rank\tilde A = 4, \; n=4$$

Система является ___совместной___ и имеет ___единственное решение___ (по теореме Кронекера — Капелли).

---

## Задание 4

Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

___Решение___

Систему можно считать несовместной, если $rankA < rank \tilde{A}$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$$

$$A=\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}$$

Найдем ранги, преобразовав расширенную матрицу $\tilde{A}$:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
6 & 6 & 6
\end{matrix}\right|
\begin{matrix}
a\\ 
b-a\\
c-a
\end{matrix}
\end{pmatrix}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-a\\
c-2b+a
\end{matrix}
\end{pmatrix}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-2b+a
\end{matrix}
\end{pmatrix}$$

Сразу можно подметить, что $rankA=2$. Для выполнения $rankA < rank \tilde{A}$ нужно, чтобы $rank \tilde{A} = 3$.

Если $c-2b+a \neq 0$, тогда система считается несовместной, что нам и нужно. В противном случае система будет совместной.

Таким образом, первое необходимое условие: $$c-2b+a \neq 0$$



Чтобы ранг расширенной матрицы $\tilde{A}$ равнялся 3 нужно, чтобы был хотя бы один ненулевой минор 3-го порядка. Причем этот минор будет содержать 4-ый столбец, так как в остальных столбцах все элементы 3-ей строки равны $0$. Таким образом, следующие условия:

$$\begin{vmatrix}
2 & 3 & a\\ 
1 & 0 & b-2a\\ 
0 & 0 & c-2b+a
\end{vmatrix} = -3\cdot(c-2b+a) \neq 0  
$$ 

или 

$$\begin{vmatrix}
1 & 3 & a\\ 
2 & 0 & b-2a\\ 
0 & 0 & c-2b+a
\end{vmatrix} = -6\cdot(c-2b+a) \neq 0  
$$

или

$$\begin{vmatrix}
1 & 2 & a\\ 
2 & 1 & b-2a\\ 
0 & 0 & c-2b+a
\end{vmatrix} = c-2b+a - 2\cdot(2c-4b+2) \neq 0  
$$


То есть
$$
\left[
\begin{gathered}
    -3\cdot(c-2b+a) \neq 0 \\
    -6\cdot(c-2b+a) \neq 0 \\
    c-2b+a - 2\cdot(2c-4b+2) \neq 0
\end{gathered} \implies
\right[ \begin{gathered}
    -3c+6b-3a \neq 0 \\
    -6c+12b-6a \neq 0 \\
    -3c+6b-3a \neq 0
\end{gathered} \implies c-2b+a \neq 0 $$

Снова получили такое же условие. Следовательно, система несовместа при $c-2b+a \neq 0$

___Ответ:___ Система считается несовместной, если $c-2b+a \neq 0$

---

# Практическое задание №4 по теме "Линейные преобразования". Часть 2

## Задание 1

Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

___Решение___

   __а)__ $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Найдём определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
1 & -2 \\
3 & -4 
\end{vmatrix}=2\neq 0$$

Найдём определители $detA_{1}$, $detA_{2}$:

$$detA_{1}=\begin{vmatrix}
1 & -2 \\
7 & -4 
\end{vmatrix}=-4+14=10$$

$$detA_{2}=\begin{vmatrix}
1 & 1 \\
3 & 7 
\end{vmatrix}=7-3=4$$

Найдём решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$


Проверка:

In [2]:
A = np.array([[1, -2], [3, -4]])
b = np.array([[1], [7]])
np.linalg.solve(A, b)

array([[5.],
       [2.]])

   __б)__ $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Найдём определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix}=2\cdot(1+12) + 7 + 5\cdot(4-2)=43\neq 0$$

Найдём определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5 \\
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix}=10\cdot13 + 1 + 5\cdot(-9)=86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5 \\
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix}=2-10\cdot 7 + 5\cdot 5 = -43$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10 \\
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix}=2\cdot9 + 5 + 10\cdot2=43$$

Найдём решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

Проверка:

In [3]:
A = np.array([[2,-1,5], [1,1,-3], [2,4,1]])
b = np.array([[10], [-2], [1]])
np.linalg.solve(A, b)

array([[ 2.],
       [-1.],
       [ 1.]])

___Ответ:___ ___а)___ $x = \begin{pmatrix}5\\2 \end{pmatrix}$, ___б)___ $x = \begin{pmatrix}2\\-1\\1 \end{pmatrix}$

---

## Задание 2*

Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

___Решение___

   __а)__ $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

Умножим первую строку на 2 и вычтем из второй, умножим первую строку на 3 и вычтем из третьей:

$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & l_{22} & 0 \\ 
3 & l_{32} & l_{33}
\end{pmatrix}$$ 

Умножим вторую строку на 4 и вычтем из третьей:

$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$ 

Проверка:

In [4]:
A = np.array([[1,2,4], [2,9,12], [3,26,30]])
L = np.array([[1,0,0], [2,1,0], [3,4,1]])
U = np.array([[1,2,4], [0,5,4], [0,0,2]])
print(f"A-LU=\n{A - np.dot(L, U)}")

A-LU=
[[0 0 0]
 [0 0 0]
 [0 0 0]]


   __б)__ $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

Умножим первую строку на 2 и вычтем из второй, умножим первую строку на 3 и вычтем из третьей? умножим первую строку на 4 и вычтем из четвертой:

$$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & l_{22} & 0 & 0\\ 
3 & l_{32} & l_{33} & 0\\
4 & l_{42} & l_{43} & l_{44}\\
\end{pmatrix}$$ 

Умножим вторую строку на 5 и вычтем из третьей, умножим вторую строку на 6 и вычтем из четвертой:

$$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & l_{33} & 0\\
4 & 6 & l_{43} & l_{44}\\
\end{pmatrix}$$ 

Умножим третью строку на 7 и вычтем из четвертой:

$$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1\\
\end{pmatrix}$$ 

Проверка:

In [5]:
A = np.array([[1,1,2,4], [2,5,8,9], [3,18,29,18], [4,22,53,33]])
L = np.array([[1,0,0,0], [2,1,0,0], [3,5,1,0], [4,6,7,1]])
U = np.array([[1,1,2,4], [0,3,4,1], [0,0,3,1], [0,0,0,4]])
print(f"A-LU=\n{A - np.dot(L, U)}")

A-LU=
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


___Ответ:___ 

___а)___ $L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

___б)___ $L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1\\
\end{pmatrix}$

---

## Задание 3*

Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

___Решение___

$$A=\begin{pmatrix}
2 & 1 & 3\\
11 & 7 & 5\\
9 & 8 & 4
\end{pmatrix}, \; b=\begin{pmatrix}
1\\
-6 \\
-5
\end{pmatrix}$$

Найдем матрицы $L$ и $U$:

$$U = \begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}, \; L = \begin{pmatrix}
l_{11} & 0 & 0 \\ 
l_{21} & l_{22} & 0 \\ 
l_{31} & l_{32} & l_{33}
\end{pmatrix}$$ 

$$U = \begin{pmatrix}
2 & 1 & 3\\ 
0 & 1.5 & -11.5\\ 
0 & 3.5 & -9.5
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & l_{22} & 0 \\ 
4.5 & l_{32} & l_{33}
\end{pmatrix}$$ 

$$U = \begin{pmatrix}
2 & 1 & 3\\ 
0 & 1.5 & -11.5\\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}, \; L = \begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & \frac{7}{3} & 1
\end{pmatrix}$$ 

Находим $y$: 

$$Ly=b$$

$$\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & \frac{7}{3} & 1
\end{pmatrix} \begin{pmatrix}
y_{1}\\
y_{2} \\
y_{3}
\end{pmatrix} = \begin{pmatrix}
1\\
-6 \\
-5
\end{pmatrix}
$$

$$\begin{cases}
y_{1} = 1 \\
y_{2} = -6 - 5.5y_{1} \\
y_{3} = -5 - 4.5y_{1} - \frac{7}{3}y_{2}
\end{cases}$$

$$y_{1}=1$$
$$y_{2}=-11.5$$
$$y_{3}=\frac{52}{3}$$

Находим $x$ обратной подстановкой:

$$Ux=y$$

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix} \begin{pmatrix}
x_{1}\\
x_{2} \\
x_{3}
\end{pmatrix} = \begin{pmatrix}
1\\
-11.5 \\
\frac{52}{3}
\end{pmatrix}
$$

$$\begin{cases}
x_1 = \frac{1-3}{2}\\
x_2 = 0\\
x_3 = 1
\end{cases}$$

$$x_{1}=-1$$
$$x_{2}=0$$
$$x_{3}=1$$

Проверка:

In [6]:
A = np.array([[2,1,3], [11,7,5], [9,8,4]])
b = np.array([[1], [-6], [-5]])
np.linalg.solve(A, b)

array([[-1.],
       [ 0.],
       [ 1.]])

___Ответ:___ $x = \begin{pmatrix}-1\\ 0\\ 1 \end{pmatrix}$

---

## Задание 4*

Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

___Решение___

$$A=\begin{pmatrix}
81 & -45 & 45\\
-45 & 50 & -15\\
45 & -15 & 38
\end{pmatrix}, \; b=\begin{pmatrix}
1\\
-6 \\
-5
\end{pmatrix}$$

Матрица $A$ симметричная, $A=A^{T}$. Для решения системы воспользуемся  методом Холецкого.

$$A=LL^{T}$$
$$l_{ii}=\sqrt{a_{ii}-\sum_{k=1}^{i-1}l_{ik}^{2}}$$
$$l_{ij}=\frac{1}{l_{jj}}\left( a_{ij}-\sum_{k=1}^{j-1}l_{ik}l_{jk}\right ), \; j < i$$

$$Ly=b$$
$$L^{T}x=y$$

Произведём разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{31}l_{21}\right)=\frac{1}{5}\cdot (-15 + 5\cdot 5)=2$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3$$

Получили матрицу:

$$L = \begin{pmatrix}
9 & 0 & 0\\ 
-5 & 5 & 0\\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5\\ 
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}$$

Решим систему $Ly=b:$

$$\begin{cases}
y_1 = \frac{1}{9}\\
y_2 = \frac{-6 + 5y_1}{5}\\
y_3 = \frac{-5 -5y_1 -2y_{2}}{3}
\end{cases}$$

$$y_{1} = \frac{1}{9}$$
$$y_{2} = -\frac{49}{45}$$
$$y_{3} = -\frac{152}{135}$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
x_3 = \\
x_2 = -\frac{49}{225}-\frac{2}{5} x_{3}\\
x_3 = - \frac{152}{405}
\end{cases}$$

$$x_{3}=- \frac{152}{405} = -0.37530864$$

$$x_{2}=-\frac{49}{225} + \frac{2}{5} \cdot \frac{152}{405} = -0.06765432$$

$$x_{1}=\frac{\frac{1}{9} + 5x_2 - 5x_3}{9}=0.18326475$$

Проверка:

In [7]:
A = np.array([[81,-45,45], [-45,50,-15], [45,-15,38]])
L = np.linalg.cholesky(A)
L_T = L.T
print(f"L=\n{L}")
print(f"L_T=\n{L_T}")

L=
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]
L_T=
[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]


In [8]:
x_2 = -49/225 + 2/5 * 152/405
x_3 = - 152/405
x_1 = (1/9 + 5*x_2 - 5*x_3)/9
print(f"x_1={np.round(x_1, 8)}")
print(f"x_2={np.round(x_2, 8)}")
print(f"x_3={np.round(x_3, 8)}")

x_1=0.18326475
x_2=-0.06765432
x_3=-0.37530864


In [9]:
b = np.array([1, -6, -5])
np.linalg.solve(A, b)

array([ 0.18326475, -0.06765432, -0.37530864])

___Ответ:___ $x = \begin{pmatrix}0.18326475\\ -0.06765432\\ -0.37530864 \end{pmatrix}$

---

## Задание 5*

Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

___Решение___

_Реализация метода Крамера для решения СЛАУ._

Для системы с $n$ уравнениями и $n$ неизвестными, если система уравнений не вырождена ($detA\neq 0$), то система определена, то есть имеет единственное решение, и это решение может быть найдено по формуле Крамера:

$$x_{i}=\frac{detA_{i}}{detA},$$

где $A_{i}$ — это матрица, получаемая заменой $i$-го столбца на вектор-столбец свободных членов $b$.

In [10]:
def minor(A, i, j):
    M = copy.deepcopy(A) 
    del M[i]
    for i in range(len(A[0])-1):
        del M[i][j]
    return M   

In [11]:
def det(A: list) -> float:
    '''
    Calculation of the matrix determinant without checking the dimension.
    '''
    n = len(A[0])
    if n == 1:
        return A[0][0]
    signum = 1
    determinant = 0
    for j in range(n):
        determinant += A[0][j]*signum*det(minor(A, 0, j)) 
        signum *= -1
    return determinant

In [12]:
def solve_cramer(A: list, B: list) -> list:
    '''
    A function that implements Cramer's rule for solving a system of linear equations. 
    If the multiplication condition is not met, an error will be generated.
    '''
    if type(A[0]) != list:
        print(f"The A list must be two-dimensional.")
        return
    if type(B[0]) == list:
        print(f"The B list must be one-dimensional.")
        return
    ncols = len(A[0])
    nrows = len(A)
    a_shape = (nrows, ncols)
    b_shape = (len(B), 1)
    if a_shape[0] != a_shape[1]:
        print(f"The matrix is not square: {a_shape}. Cramer's method is not applicable.")
        return
    if b_shape[0] != a_shape[1]:
        print(f"Shapes {a_shape} and {b_shape} not aligned: {a_shape[1]} (dim 1) != {b_shape[0]} (dim 0)")
        return
    
    # n=1
    if ncols == 1:
        return [B[0]/A[0][0]]
    
    # n>1
    det_A = det(A)
    X = []
    for j in range(ncols):
        replacement_matrix = copy.deepcopy(A)
        for i in range(nrows):
            replacement_matrix[i][j] = B[i]
        det_rep_matrix = det(replacement_matrix)
        x_j = det_rep_matrix/det_A
        X.append(x_j)
    return X    

Проверка:

№1

In [13]:
A = [[1,2,4],[5,1,2],[3,-1,1]]
B = [31, 29, 10]
solve_cramer(A, B)

[3.0, 4.0, 5.0]

In [14]:
np.linalg.solve(A, B)

array([3., 4., 5.])

№2

In [15]:
A = [[1,-1,3,1],[4,-1,5,4],[2,-2,4,1],[1,-4,5,-1]]
B = [5, 4, 6, 3]
solve_cramer(A, B)

[9.0, 18.0, 10.0, -16.0]

In [16]:
np.linalg.solve(A, B)

array([  9.,  18.,  10., -16.])

---