# Матрицы и матричные операции. Часть 1

In [1]:
import numpy as np

## Задание 1

Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


___Решение___

а) Произведения матриц __AB__ и __BA__ не определены. $2 \neq 4$

б) Произведение __AB__ определено, так как $5 = 5$. Произведение __BA__ не определено, т.к. $3 \neq 2$. Размерность матрицы $C = AB$ — $2\times 3$

в) Произведение __AB__ определено, так как $3 = 3$. Размерность получаемой, таким образом, матрицы $С = AB$ — $8\times 8$.

Произведение __BA__ определено, так как $8=8$. Размерность матрицы $D = BA$ — $3\times 3$.

г) Произведение __AB__ и __BA__ определено так как матрицы квадратные размерностью $4\times 4$.  Размерность матрицы $С = AB$ и $D = BA$ — $4\times 4$

---

## Задание 2

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



___Решение___

$$A + B = 
\begin{pmatrix}
1 & -2 \\
3 & 0\\
\end{pmatrix} + \begin{pmatrix}
4 & -1 \\
0 & 5\\
\end{pmatrix}
= 
\begin{pmatrix}
5 & -3 \\
3 & 5\\
\end{pmatrix}
$$

$$A \cdot B = 
\begin{pmatrix}
1 & -2 \\
3 & 0\\
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1 \\
0 & 5\\
\end{pmatrix}
=
\begin{pmatrix}
4 & -11 \\
12 & -3\\
\end{pmatrix}
$$

$$B \cdot A = 
\begin{pmatrix}
4 & -1 \\
0 & 5\\
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2 \\
3 & 0\\
\end{pmatrix} \cdot 
=
\begin{pmatrix}
1 & -8 \\
15 & 0\\
\end{pmatrix}
$$

Проверка:

In [2]:
A = np.array([[1, -2],[3, 0]])
B = np.array([[4, -1],[0, 5]])

In [3]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [4]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

In [5]:
B @ A

array([[ 1, -8],
       [15,  0]])

---

## Задание 3

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$

___Решение___

$$3A-2B+4C = 3 \cdot
\begin{pmatrix}
1 & 7 \\
3 & -6\\
\end{pmatrix} - 2 \cdot \begin{pmatrix}
0 & 5 \\
2 & -1 \\
\end{pmatrix} + 4 \cdot \begin{pmatrix}
2 & -4\\
1 & 1\\
\end{pmatrix} =
$$

$$ = 
\begin{pmatrix}
3 & 21\\
9 & -18\\
\end{pmatrix} + \begin{pmatrix}
0 & -10\\
-4 & 2\\
\end{pmatrix} + \begin{pmatrix}
8 & -16\\
4 & 4\\
\end{pmatrix} = 
$$

$$ = \begin{pmatrix}
3 & 11\\
5 & -16\\
\end{pmatrix} +
\begin{pmatrix}
8 & -16\\
4 & 4\\
\end{pmatrix} = \begin{pmatrix}
11 & -5\\
9 & -12\\
\end{pmatrix} 
$$

Проверка:

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

---

## Задание 4

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

___Решение___

$$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}, \;\;
A^{T} = \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3\\
\end{pmatrix}$$

$$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3\\
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3\\
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13\\
\end{pmatrix}
$$

$$A^{T} = \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3 \\
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3 \\
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14 \\
\end{pmatrix}
$$

Проверка:

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T

In [8]:
A @ A_T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [9]:
A_T @ A

array([[45,  0],
       [ 0, 14]])

---

## Задание 5*

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

___Решение___

In [10]:
def matrix_multiplication(A, B):
    '''
    The function of multiplying matrix A by matrix B. If the multiplication condition is not met, an error will be generated.
    '''
    # shape
    ncols = len(A[0])
    nrows = len(A)
    a_shape = (nrows, ncols)
    ncols = len(B[0])
    nrows = len(B)
    b_shape = (nrows, ncols)
    l = a_shape[0]
    m = a_shape[1]
    n = b_shape[1]
    # check
    if b_shape[0] != a_shape[1]:
        print(f"Shapes {a_shape} and {b_shape} not aligned: {a_shape[1]} (dim 1) != {b_shape[0]} (dim 0)")
        return
    else:
        # check n columns in every row
        ncols_wrong_idx = [i for i in range(a_shape[0]) if len(A[i]) != a_shape[1]]
        if len(ncols_wrong_idx) != 0:
            print(f"Matrix A is set incorrectly! Check the elements of matrix A on the rows: {ncols_wrong_idx}")
            return
        
        ncols_wrong_idx = [i for i in range(b_shape[0]) if len(B[i]) != b_shape[1]]
        if len(ncols_wrong_idx) != 0:
            print(f"Matrix B is set incorrectly! Check the elements of matrix B on the rows: {ncols_wrong_idx}")
            return
    
    # calculate, after check
    result_matrix = []
    for i in range(l):
        row = []
        for j in range(n):
            el = sum(list([A[i][r] * B[r][j] for r in range(m)]))
            row.append(el)
        result_matrix.append(row)
    return result_matrix
    

Проверка:

In [11]:
A = [[3, 5, 7,], [2, 5, 8], [-2, 4, -12], [0, 33, 11]]
B = [[9, 16, -2, 11, 1], [-3, -7, 17, 9, -14], [-13, 5, -3, 4, -12]]

In [12]:
res = matrix_multiplication(A, B)
res

[[-79, 48, 58, 106, -151],
 [-101, 37, 57, 99, -164],
 [126, -120, 108, -34, 86],
 [-242, -176, 528, 341, -594]]

In [13]:
np.array(res)

array([[ -79,   48,   58,  106, -151],
       [-101,   37,   57,   99, -164],
       [ 126, -120,  108,  -34,   86],
       [-242, -176,  528,  341, -594]])

In [14]:
np.dot(A, B)

array([[ -79,   48,   58,  106, -151],
       [-101,   37,   57,   99, -164],
       [ 126, -120,  108,  -34,   86],
       [-242, -176,  528,  341, -594]])

---

# Матрицы и матричные операции. Часть 2

## Задание 1

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

___Решение___

а) 

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} 
= \sin{x}^{2} + \cos{x}^{2} = 1$$

б) 

$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot 5\cdot 9 = 180$$

In [15]:
B = np.array([[4,2,3],[0,5,1],[0,0,9]])
np.linalg.det(B)

180.0

в) $$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{vmatrix} = 0
$$

In [16]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.round(np.linalg.det(C), 8)

0.0

---

## Задание 2

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

___Решение___

$$det(A) = 4$$

а) $det(A^{2})$ — ?

Воспользуемся свойствами определителей, а именно: $det(AB)=detA\cdot detB$

$$det(A^{2}) = det(A\cdot A) = det(A)\cdot det(A) = 4\cdot 4 = 16$$

б) $det(A^{T})$ — ?

Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA=4$$

в) $det(2A)$ — ?

Зная свойства определителей, знаем, что умножение одной строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. 

Пусть матрица $A$ имеет размерность $n\times n$, т.е. $n$ - строк, $n$ - столбцов.

Матрица $2A$ означает, что каждую строку умножили на $2$. Таким образом, в соответствие со свойством, определитель матрицы должен измениться в $2^{n}$, так как в нашем случае умножилась не одна строка, а сразу $n$ строк.

$$det(\lambda\cdot A) = det(A)\cdot \lambda^{n}$$

Поскольку в задании не указана размерность матрицы, а дано лишь значение ее определителя, то:

$$det(2A) = det(A)\cdot 2^{n} = 4 \cdot 2^{n} = 2^{n+2},$$

где $n$ - размерность квадратной матрицы $A$

---

## Задание 3

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


___Решение___

Матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю. Найдем определитель.

Прибавим ко второй строке первую, умноженную на $2$

$$ det \begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = \begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = \begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix} = 0
$$

Определитель данной матрицы равен нулю, соответсвенно матрица вырожденная.

---

## Задание 4

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

___Решение___

а) Найдем ранг матрицы

$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$$

Третья строка является суммой второй и первой строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
\end{pmatrix}$$

Из второй строки вычтем первую:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
\end{pmatrix}$$

Таким образом, ранг матрицы равен $2$.

In [17]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б) Найдем ранг матрицы

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

Третья строка является суммой второй и первой строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}$$

Вычтем из первой строки вторую:
$$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}$$

Таким образом, ранг матрицы равен $3$.

In [18]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(B)

3

---